### ISSUE TITLE
Installing Swipeable Modal

### ISSUE THREAD

**Issue by armcast** [apolkingg8/React-Native-Swipeable-Modal#1]
Hi, 

I seem to be having some problems on install. I run the command as stated in the README but then when I try to require the module in my code using: 
````
var Modal = require('react-native-swipeable-modal');
````

I get errors in the simulator stating
````
SyntaxError: Unexpected end of script

{
"line": 46590
"sourceURL": "http://localhost:8081/index.os.bundle"
}
````

Any ideas? Thanks in advance.

**Comment by apolkingg8** [comment]
@armcast  did you trace the code stack from `http://localhost:8081/index.os.bundle` `line:46590` ? I'm afraid I need more information with that.

**Comment by armcast** [comment]
This error is caused by requiring "react-native-swipeable-modal"

is this correct?

**Comment by apolkingg8** [comment]
What's your `React-Native` version? I tried that with `0.6.0-rc` and it works fine. If you are using `0.5.0` or earlier, try remove [this line](https://github.com/apolkingg8/React-Native-Swipeable-Modal/blob/master/index.js#L217). Hope this helps.

**Comment by apolkingg8** [comment]
Seams it's caused this [packager issue](https://github.com/facebook/react-native/issues/1431), resolved with [this commit](https://github.com/nicklockwood/react-native/commit/477360b8c95320b90cd6314022e761bc495182d0).

**Comment by armcast** [comment]
Hi, 

I updated my version of react-native-swipeable-modal to the latest release (1.1.6) and I am on react native version 0.5 and everything is working as expected!

Thanks for your help and time.

**Comment by apolkingg8** [comment]
Great to hear that!
