### ISSUE TITLE
Question: Is it possible to force bringing modal to the front? (over TabBar / NavigationBars etc)

### ISSUE THREAD

**Issue by MossP** [apolkingg8/React-Native-Swipeable-Modal#2]
I notice when using this with SMXTabBar (and likely TabBarIOS) that the modal shows behind the TabBar.

**Comment by MossP** [comment]
ps.. Nice Component :+1:

**Comment by apolkingg8** [comment]
What's your render flow? Try put `Modal` render after `TabBarIOS `, just like that:
```js
render: function() {
  return (
    <View>
      <TabBarIOS/>
      <Modal/>
    </View>
  )
}
```
it works for me. See [vjeux's comment in this issue](https://github.com/facebook/react-native/issues/131), that maybe helpful.

ps: Thanks for your ps :smile:

**Comment by MossP** [comment]
Not sure how I missed your reply, but thank you for getting back to me. Doing what you said made the TabBar invisible for me (and all of the content contained within. I think I'll need to look a little more into it. I'll post back if I get a solution.

**Comment by apolkingg8** [comment]
close because out of date.
