### ISSUE TITLE
Is it possible to have a touchable inside the modal?

### ISSUE THREAD

**Issue by bradens** [apolkingg8/React-Native-Swipeable-Modal#3]
The modal always seems to take the tap...

**Comment by apolkingg8** [comment]
I builded `swipeableAreaStyle ` for this issue, that's enough in my case (but I think something like `unSwipeableAreaStyles` will be better). Can you describe more about your use case?

**Comment by bradens** [comment]
I have a listview of touchable items that i'm bringing up in the modal, I ended up forking your project and just using it without the swipe gestures.

**Comment by apolkingg8** [comment]
That's similar with my case. Does the `ListVew` have a head bar ? If yes, you can set `swipeableAreaStyle ` like that: 
```
{
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: headBarHeight,
    backgroundColor: 'transparent'
}
```
or you want disable swipe gestures:
```
{
    width: 0,
    height: 0
}
```
that works with me. I can't find the way let `Touchable*` works in `swipeableArea` at this time. Feel free to reopen it if you have better idea :)

**Comment by bradens** [comment]
Good call, I ended up just making the header swipeable.
