### ISSUE TITLE
Why is the modalStyle property taking an object instead of a React StyleSheet?

### ISSUE THREAD

**Issue by lukasreichart** [apolkingg8/React-Native-Swipeable-Modal#4]
See title.

**Comment by apolkingg8** [comment]
I can add the `StyleSheet` support for `*Style` props, that's not hard at all. But if I get a StyleSheet ref and tween it, that means I changing something outside the modal, that's not a good ideal. If I clone the ref and tween a new object, there's no different with use an object from props. Excuse my poor English, hope you can understand what i mean :)

**Comment by apolkingg8** [comment]
Done.
